from __future__ import annotations

from contextlib import asynccontextmanager
from datetime import datetime
from random import choice, randint, random
from typing import Any

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from .database import get_record, init_db, list_records, save_record, update_record
from .agent_runtime import AGENT_DEFINITIONS, list_providers, run_agent
from .otel import SAMPLE_OTEL_PAYLOAD, normalize_otel_payload, replay_trace
from .schemas import (
    AgentRuntime,
    AgentDefinition,
    AgentRunRecord,
    AgentRunRequest,
    AgentRunResponse,
    CostSummary,
    DashboardSnapshot,
    Evaluator,
    Incident,
    IncidentPatch,
    OtelIngestRequest,
    OtelIngestResult,
    Policy,
    PolicyTestRequest,
    PolicyTestResult,
    ProviderStatus,
    PromptVersion,
    RagQuery,
    ReplayResult,
    SettingsPayload,
    Stats,
    Trace,
)


@asynccontextmanager
async def lifespan(_app: FastAPI):
    init_db()
    yield


app = FastAPI(title="NeuralOps Platform API", version="0.1.0", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
def health() -> dict[str, Any]:
    return {"ok": True, "service": "neuralops-api", "version": app.version}


@app.get("/api/dashboard", response_model=DashboardSnapshot)
def dashboard() -> DashboardSnapshot:
    stats = Stats.model_validate(get_record("stats", "current"))
    traces = [Trace.model_validate(item) for item in list_records("traces")]
    incidents = [Incident.model_validate(item) for item in list_records("incidents")]
    return DashboardSnapshot(stats=stats, traces=traces[:50], incidents=incidents)


@app.get("/api/traces", response_model=list[Trace])
def traces() -> list[Trace]:
    return [Trace.model_validate(item) for item in list_records("traces")]


@app.get("/api/traces/{trace_id}", response_model=Trace)
def trace_detail(trace_id: str) -> Trace:
    trace = get_record("traces", trace_id)
    if trace is None:
        raise HTTPException(status_code=404, detail="Trace not found")
    return Trace.model_validate(trace)


@app.post("/api/traces/otel", response_model=OtelIngestResult)
def ingest_otel_trace(request: OtelIngestRequest) -> OtelIngestResult:
    try:
        trace, findings = normalize_otel_payload(request.payload, request.environment)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    save_record("traces", trace.id, trace.model_dump())
    decision = "block" if trace.status == "blocked" else "review" if trace.status == "warning" else "allow"
    return OtelIngestResult(decision=decision, trace=trace, spanCount=trace.spanCount, findings=findings)


@app.post("/api/traces/otel/sample", response_model=OtelIngestResult)
def ingest_sample_otel_trace() -> OtelIngestResult:
    trace, findings = normalize_otel_payload(SAMPLE_OTEL_PAYLOAD, "prod")
    save_record("traces", trace.id, trace.model_dump())
    return OtelIngestResult(decision="block", trace=trace, spanCount=trace.spanCount, findings=findings)


@app.post("/api/traces/{trace_id}/replay", response_model=ReplayResult)
def replay_existing_trace(trace_id: str) -> ReplayResult:
    trace = get_record("traces", trace_id)
    if trace is None:
        raise HTTPException(status_code=404, detail="Trace not found")
    return replay_trace(trace)


@app.post("/api/traces/simulate", response_model=Trace)
def simulate_trace() -> Trace:
    model = choice(["gpt-4o", "claude-3.5-sonnet", "gpt-4o-mini", "llama-3.1-70b"])
    status = "failed" if random() > 0.92 else "warning" if random() > 0.85 else "success"
    tokens = randint(400, 1900)
    trace = {
        "id": f"tr_api_{randint(1000, 9999)}",
        "timestamp": datetime.now().strftime("%H:%M:%S"),
        "session": f"sess_{randint(1000, 9999)}",
        "environment": "prod",
        "model": model,
        "tokens": tokens,
        "latency": f"{random() * 2 + 0.3:.2f}s",
        "cost": f"${tokens * 0.000015:.3f}",
        "status": status,
        "score": 0.0 if status == "failed" else round(random() * 0.2 + 0.75, 2),
        "prompt": "Simulated API client request prompt.",
        "output": f"Simulated output generated by {model}.",
        "toolCalls": "web_search_connector" if random() > 0.75 else None,
    }
    return Trace.model_validate(save_record("traces", trace["id"], trace))


@app.get("/api/incidents", response_model=list[Incident])
def incidents() -> list[Incident]:
    return [Incident.model_validate(item) for item in list_records("incidents")]


@app.patch("/api/incidents/{incident_id}", response_model=Incident)
def patch_incident(incident_id: str, patch: IncidentPatch) -> Incident:
    updated = update_record("incidents", incident_id, patch.model_dump(exclude_unset=True))
    if updated is None:
        raise HTTPException(status_code=404, detail="Incident not found")
    return Incident.model_validate(updated)


@app.get("/api/prompts", response_model=list[PromptVersion])
def prompts() -> list[PromptVersion]:
    return [PromptVersion.model_validate(item) for item in list_records("prompts")]


@app.post("/api/prompts/{prompt_id}/deploy", response_model=PromptVersion)
def deploy_prompt(prompt_id: str) -> PromptVersion:
    prompt = get_record("prompts", prompt_id)
    if prompt is None:
        raise HTTPException(status_code=404, detail="Prompt not found")
    prompt["status"] = "Production"
    prompt["canaryPercent"] = 100
    prompt["updatedAt"] = datetime.now().isoformat()
    return PromptVersion.model_validate(save_record("prompts", prompt_id, prompt))


@app.get("/api/evals", response_model=list[Evaluator])
def evals() -> list[Evaluator]:
    return [Evaluator.model_validate(item) for item in list_records("evals")]


@app.post("/api/evals/run", response_model=list[Evaluator])
def run_evals() -> list[Evaluator]:
    records = []
    for evaluator in list_records("evals"):
        evaluator["lastRun"] = "just now"
        evaluator["passRate"] = min(0.99, round(float(evaluator["passRate"]) + 0.01, 2))
        records.append(save_record("evals", evaluator["id"], evaluator))
    return [Evaluator.model_validate(item) for item in records]


@app.get("/api/rag", response_model=list[RagQuery])
def rag() -> list[RagQuery]:
    return [RagQuery.model_validate(item) for item in list_records("rag")]


@app.get("/api/costs")
def costs() -> dict[str, Any]:
    return get_record("costs", "current") or {}


@app.post("/api/costs/simulate-anomaly")
def simulate_cost_anomaly() -> dict[str, Any]:
    costs_payload = get_record("costs", "current") or {}
    summary = CostSummary.model_validate(costs_payload.get("summary", {}))
    costs_payload["summary"] = {
        **summary.model_dump(),
        "mtdSpend": round(summary.mtdSpend + 120.40, 2),
        "projectedSpend": round(summary.projectedSpend + 420.0, 2),
    }
    save_record("costs", "current", costs_payload)
    return {
        "decision": "review",
        "reason": "Spend spike detected in prod_rag_qa workspace.",
        "summary": costs_payload["summary"],
    }


@app.get("/api/policies", response_model=list[Policy])
def policies() -> list[Policy]:
    return [Policy.model_validate(item) for item in list_records("policies")]


@app.post("/api/policies/test", response_model=PolicyTestResult)
def test_policy(request: PolicyTestRequest) -> PolicyTestResult:
    text = request.input.lower()
    critical_patterns = ["ignore previous", "ignore standard", "password", "api key", "secret", "token"]
    matched = [pattern for pattern in critical_patterns if pattern in text]
    if matched:
        return PolicyTestResult(
            decision="block",
            severity="Critical",
            reason="Input matched prompt-injection or credential exfiltration patterns.",
            matchedPatterns=matched,
        )
    if "external" in text or "send" in text or "webhook" in text:
        return PolicyTestResult(
            decision="review",
            severity="Major",
            reason="Input asks for external communication or tool use and requires approval.",
            matchedPatterns=["external-tool"],
        )
    return PolicyTestResult(decision="allow", severity=None, reason="No configured policy matched.", matchedPatterns=[])


@app.get("/api/agents", response_model=list[AgentRuntime])
def agents() -> list[AgentRuntime]:
    return [AgentRuntime.model_validate(item) for item in list_records("agents")]


@app.get("/api/agent-runtime/definitions", response_model=list[AgentDefinition])
def agent_definitions() -> list[AgentDefinition]:
    return AGENT_DEFINITIONS


@app.get("/api/agent-runtime/providers", response_model=list[ProviderStatus])
def provider_status() -> list[ProviderStatus]:
    return list_providers()


@app.get("/api/agent-runtime/runs", response_model=list[AgentRunRecord])
def agent_runs() -> list[AgentRunRecord]:
    return [AgentRunRecord.model_validate(item) for item in list_records("agent_runs")]


@app.get("/api/agent-runtime/runs/{run_id}", response_model=AgentRunRecord)
def agent_run_detail(run_id: str) -> AgentRunRecord:
    run = get_record("agent_runs", run_id)
    if run is None:
        raise HTTPException(status_code=404, detail="Agent run not found")
    return AgentRunRecord.model_validate(run)


@app.post("/api/agent-runtime/run", response_model=AgentRunResponse)
def execute_agent(request: AgentRunRequest) -> AgentRunResponse:
    try:
        run, trace = run_agent(request)
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    save_record("agent_runs", run.id, run.model_dump())
    save_record("traces", trace.id, trace.model_dump())
    return AgentRunResponse(run=run, trace=trace)


@app.get("/api/settings", response_model=SettingsPayload)
def settings() -> SettingsPayload:
    payload = get_record("settings", "current")
    if payload is None:
        raise HTTPException(status_code=404, detail="Settings not found")
    return SettingsPayload.model_validate(payload)
